### ISSUE TITLE
Better trend arrows on highly variable stats

### ISSUE THREAD

**Issue by Luit** [minvws/nl-covid19-data-dashboard#1290]
Currently the *Number of confirmed cases* statistic is accompanied by an arrow describing what I presume is meant to be a trend. It appears to use the difference between the second-to-last data point and the last. Especially for this statistic, with a high variance and a weekly pattern, this isn't a good way to show the trend. 

Right now, the statistic shows Tuesday's 9872, down 1327 from Monday. This is more or less the same steep dive the statistic had exactly a week before. Because of this, the arrow more accurately tells you the day of the week than the trend of this statistic.

I would suggest basing this on something less sensitive to this weekly cycle by, for example, using the 7-day average which effectively means comparing a Tuesday's data point with the Tuesday before it.

**Comment by VWSCoronaDashboard** [comment]
@Luit The arrows are just meant to show whether the number has increased, decreased or stayed the same since the last data load for that metric. It helps to not have to remember what the previous value was and quickly see what has changed from last time. For viewing the trend the progression over time graph is more suited, adding a 7 day average there might make sense mainly on the municipality level (and we're looking into that v.s. the added complexity to read the chart). 

Given the use case for the arrow is different per your suggestion I'm closing this ticket. We'll keep in mind the underlying question of "how to better spot the trend on highly variable datasets" for future updates though!
