### ISSUE TITLE
Disable TLS v1 and 1.1

### ISSUE THREAD

**Issue by 1Jesper1** [minvws/nl-covid19-data-dashboard#1546]
https://github.com/minvws/nl-covid19-data-dashboard/blob/1e3d261a6db9ab2006a1f216c2876ae8a3c8bc53/nginx.conf#L42

**Comment by VWSCoronaDashboard7** [comment]
You seem to be behind quite a bit on that commit, it's from June 2020. As you can see on https://www.ssllabs.com/ssltest/analyze.html?d=coronadashboard.rijksoverheid.nl&s=23.54.147.34&hideResults=on&ignoreMismatch=on we're not actually using this in production. As such I'm closing this since it's no longer valid. See https://github.com/minvws/nl-covid19-data-dashboard/blob/develop/packages/app/nginx.conf for our recent configuration.
