### ISSUE TITLE
Chart with distribution of agegroups for positive tests and population has no time indication

### ISSUE THREAD

**Issue by cjvanzwol** [minvws/nl-covid19-data-dashboard#2050]
# Situation
https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen

The barchart with distribution of agegroups for positive tests and population has no time indication.
So it is not clear of what period this data is. 
No mention of time suggests it is data for all time. 

# Problem
The barchart has not indication of time. 

It should be clear what scope the data is about to be able to interpret it. 

# Solution
Adding a time indication to the chart of to the explanation.

**Comment by VWSCoronaDashboard7** [comment]
We're replacing this chart soon (closing it because of that) but agreed that the information on the time period is not easy to find. To answer the underlying question: it's the change towards the day before. To quote the functional documentation:

> The difference between the number of positively tested people in a certain age-group in comparison with yesterday (date is based on the field date_file); the age-groups are (0 tot 20, 20 tot 40, 40 tot 60, 60 tot 80, 80+); If the age-group is unknown or <50 these numbers are not taken into account; Every row in the input-table is an positively tested person, so a generic count is performed.

Source: https://github.com/minvws/nl-covid19-data-backend-processing/blob/master/functional_doc.md
(point 6, Positive Tested People per Age Group)
