### ISSUE TITLE
Feature request: Infectable population indicator

### ISSUE THREAD

**Issue by MMeent** [minvws/nl-covid19-data-dashboard#2370]
With the vaccination campaign getting more and more momentum, I believe that it would be interesting to get an estimate on how much of the population is not (yet) immune, i.e. `(total population) - (active covid cases) - (cured covid cases * immune factor cured covid cases) - (vaccinated people * immune factor vaccinations)`, optionally correcting for age group growth / shrinking.

Of course this would most likely be an estimate, but I believe this is an important component in getting the reproduction number down, and I believe that this number (and its breakout in components) would be very interesting to run public analysis on.

**Comment by VWSCoronaDashboard** [comment]
It's an interesting thought but the immune factor isn't known, so you can't calculate this. Aside from that I wonder what the added value is to having this number. You can sort of deduce order of magnitude from the current numbers on the dashboard. Leading me to the conclusion it's "the majority of the Netherlands" right now. But getting infected has vastly different effects depending on which group gets infected, whether they confirm to social distancing rules, age group of those infected etc so it doesn't seem like a very actionable number to me. 

I'm closing it because it's a moot point (RIVM doesn't supply this data so we have nothing to visualise) but if you have a different opinion on what this would additionally bring by all means :-)
