### ISSUE TITLE
Unable to run front-end locally

### ISSUE THREAD

**Issue by mcrapts** [minvws/nl-covid19-data-dashboard#2415]
### Describe the bug, issue or concern

I am unable to run the front-end application locally. I consistently get the error `Module not found: Can't resolve '@corona-dashboard/common'`. I followed the instructions (installed the packages by running `yarn`, didn't use `npm` that could possibly mess things up. Also `yarn test` doesn't work, tests fail with the same error.

### To Reproduce
1. Clone repository
2. Head into `packages/app`
3. Copy `.env.local.example` to `.env.local`
4. Run `yarn && yarn dev` or `yarn && yarn test`
5. Watch it fail with with the error `Module not found: Can't resolve '@corona-dashboard/common'` occurring multiple times. 

### Expected behavior
No errors.

### Additional context
My editor doesn't seem to have problems resolving `@corona-dashboad/common` so at least tsconfig.base.json is working. I am using Ubuntu (in WSL2).

**Comment by VWSCoronaDashboard** [comment]
Hi! Your step 2 is what goes wrong, please run the commands from step 3 in the root directory. Note you would also need to run "yarn download" to get the latest data files from production. Also ensure you're running the "master" branche for compatibility with the production dataset ( the default, development, may or may not be ahead and fail to build.

Lastly, due to https://github.com/minvws/nl-covid19-data-dashboard/issues/2236 you might run into issues on some pages. It's on our to-do to take a better look at enabling that. Hope this helps!

**Comment by mcrapts** [comment]
Even when doing a fresh `git clone`, switching to master branch and running `yarn` from the root directory I unfortunately run into the exact same problem.

**Comment by VWSCoronaDashboard** [comment]
> Even when doing a fresh `git clone`, switching to master branch and running `yarn` from the root directory I unfortunately run into the exact same problem.

What happens if you run `yarn compile` first?

**Comment by mcrapts** [comment]
That works! Thanks. Perhaps an idea to add this to the readme?

**Comment by C-E-Rios** [comment]
Hey thanks for steps above but still unable to run the repo after following the steps mentioned:

`error - Error: NEXT_PUBLIC_SANITY_DATASET is undefined`
