### ISSUE TITLE
Sample data not included, application doesn't load without JSONs in place

### ISSUE THREAD

**Issue by marten** [minvws/nl-covid19-data-dashboard#307]
### Describe the bug, issue or concern

I wanted to investigate reports of incorrect application of gradients on the barScale component. Unfortunately, I can't seem to get the frontend to load without putting any data in place in `public/json`, but the README doesn't specify where to get this data from.

Would it be possible to include a set of sample data with the repository for development? Or otherwise describe how to get a copy of the current data from the production dashboard (ideally a yarn command).

### To Reproduce

1. Clone a fresh copy of the repository
2. Run `yarn` as described in the README
3. Run `yarn dev` as described in the README
4. Open http://localhost:3000 and see error `Error: ENOENT: no such file or directory, open '/Users/marten/src/nl-covid19-data-dashboard/public/json/NL.json'`

### Expected behavior

Dashboard opens with static sample data. It is acceptable if there is a manual step to put the sample data in place but then that needs to be described in the README.

### Screenshots

![image](https://user-images.githubusercontent.com/277/93191030-58ed3980-f744-11ea-83f9-4fa7ebaaa1da.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Firefox Developer Edition
 - Version 81

### Additional context

n/a

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jwz104** [comment]
I was just creating the same issue! The readme specifies something about that the data needs to be put into `/public/json`, but I'm not able to get the right json data. The calculation can be found in the [nl-covid19-data-backend-processing](https://github.com/minvws/nl-covid19-data-backend-processing) repo. But I'm not able to generate the actual data.

**Comment by marten** [comment]
I've had some luck downloading the files from the production site btw, but you'll need to pull files per municipality and region.

```
mkdir public/json
curl -o public/json/NL.json https://coronadashboard.rijksoverheid.nl/json/NL.json
curl -o public/json/VR13.json https://coronadashboard.rijksoverheid.nl/json/VR13.json
```

**Comment by jwz104** [comment]
Yea a clone & run solution would be much better.

**Comment by marten** [comment]
Alternatively, if there is interest, I'd be happy to work on adding a proxying middleware to load data directly from the live site in development mode (unless a `public/json` folder exists, in which case you'd want to see that static dataset - so that you can still work against a new unpublished datatype or debug some value that only happened a few days ago).

**Comment by VWSCoronaDashboard** [comment]
Hey @marten, thanks for raising this issue!

This is something we've been talking about internally as well. This has been a lower priority for us because almost all of our resources have been put into working towards version v2.0.0, which is a significant refactor.

While that version is not live _yet_, I can tell you it's coming _soon_.

One of the exciting new features of v2.0.0 of the dashboard is static rendering. While we used a fetch to get data client-side in v1, we now serve almost everything statically. This means we read JSON files directly from the file system while building. See the [Next.js documentation](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) for more info.

There might be an option where we tell Next.js to fetch the JSON files when in development mode. Maybe with an environment variable. Is that something that would work for you? In that scenario your local clone would always talk to the latest dataset on master.

**Comment by VWSCoronaDashboard** [comment]
Hey everyone, we've added a way to download the full dataset automatically.

Please check out the latest version of the develop branch and run `yarn download`.
This should give you a working application.

**Comment by VWSCoronaDashboard** [comment]
Hey everyone, we've added a way to download the full dataset automatically.

Please check out the latest version of the develop branch and run `yarn download`.
This should give you a working application.

Let us know if you encounter any data-related bugs.
