### ISSUE TITLE
Percentage booster doses administered seems off

### ISSUE THREAD

**Issue by mzelst** [minvws/nl-covid19-data-dashboard#3956]
In the overview page of vaccination data, booster data is now reported as total boosters administered and percentage of people that has been boosted/received a third dose (for people 18 years or older, 18+ hereafter). When recalculating the number of people that have been boosted, I am unable to reproduce the percentage of boosted people, given the number of boosters administered.

The number of people that are 18+ is ~14.2 million (January 2021, source: [CBS](https://www.cbs.nl/nl-nl/visualisaties/dashboard-bevolking/leeftijd/jongeren#:~:text=Hoeveel%20jongeren%20zijn%20er%20in%20Nederland%3F&text=Er%20zijn%20681%20662%20kinderen,de%2018%20en%2025%20jaar.)). If 24.1% of 18+ has received a booster, then that would imply that ~3.4 million boosters should have been administered. However, the dashboard now reports 3.86 million boosters administered. I'm unable to reconcile these different numbers based on the current description of how the percentage is calculated.

Hence, perhaps the calculations could be updated or the description could be improved as to what is exactly calculated here.

The data in this example has been downloaded from the dashboard on January 3, 2021.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Sikerdebaard** [comment]
It looks like the accuracy of this number has been improved. This is good because if we want people to take the numbers on the dashboard seriously then basic numbers like this need to be as accurate as possible.

[CBS estimates](https://www.cbs.nl/nl-nl/visualisaties/dashboard-bevolking/bevolkingspiramide) that the 18+ group is around 14.286.000 in size for 2022. This number is a prognosis.

[The dashboard](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties) reports 7.754.197 boosters and 3th doses injected, which is reported as 53,3% of the 18+ group having received a booster shot.

`0,533 x 14.286.000 = 7.614.438` now assuming that the 3th doses are not included in the percentage number, adding those 3th doses to this number results in `7.746.408` which is close, but not exactly the same.

Furthermore, when assuming that the 3th doses are not included in the percentage of 18+ then adding the doses of GGD + other, but not 3th doses, results in `6.795.227 + 827.000 = 7.622.227` booster doses administered, which is `7.622.227 / 14.286.000 = 53,3545%` which, by most general rounding algorithms, should be rounded to 53.4%. However, it looks like the fraction was truncated after 1 decimal instead or perhaps a different data source for the 18+ population size was used resulting in slightly different results.

In any case, with the assumption that 3th doses are not included in the percentage of the 18+ population I think it is safe to conclude that the current imprecision, albeit small, could be attributed to rounding or precision errors.

**Comment by VWSCoronaDashboard18** [comment]
Hi @mzelst,

Thanks for asking your question. This issue is not frontend code related, therefore we cannot answer your question here. Any questions regarding data calculations or explanations of data can be sent via email to coronadashboard@minvws.nl.

Or take a look at the contact page of the dashboard.
[https://coronadashboard.rijksoverheid.nl/contact](https://coronadashboard.rijksoverheid.nl/contact)
