### ISSUE TITLE
Explanation on how sewer data is aggregated is unclear

### ISSUE THREAD

**Issue by fritshermans** [minvws/nl-covid19-data-dashboard#4285]
Currently, the description of how to create sewer data on aggregated (=country) level that is presented in the dashboard is unclear. With the description (shown below), I'm not able to replicate the numbers shown on the dashboard using the raw csv file from the RIVM website.

_Berekening gemiddeld aantal virusdeeltjes
Iedere dag publiceert het dashboard het gemiddelde aantal virusdeeltjes per 100.000 inwoners. Om dit getal te berekenen, gebruiken we de laatste meting van elke rioolwaterzuiveringsinstallatie. De laatste meting van een zuiveringsinstallatie kan meerdere dagen meetellen in de berekening.
Alle rioolwaterzuiveringsinstallaties verzamelen gemiddeld vier keer per week monsters die door het RIVM worden gemeten. Als op maandag, woensdag en zaterdag een nieuwe meting wordt doorgegeven, telt de uitslag van de meting van woensdag ook mee op donderdag en vrijdag. Alleen als de laatste meting ouder is dan negen dagen, telt die niet mee in het gemiddelde._

When I read the above, I conclude that I should create a pivot table from the raw csv file where rows are dates and columns are municipalities. Then I fill the missing values using a forward fill with a limit of 9 days. Then I take a row wise mean to get a mean level per date. This method however does not result in the same numbers as shown in the dashboard.

**Comment by VWSCoronaDashboard18** [comment]
Hi @fritshermans,

Thanks for asking your question. This issue is not code related, therefore we cannot answer your question here. Any questions regarding data calculations or explanation of data can be sent via email to coronadashboard@minvws.nl.

Or take a look at the contact page of the dashboard.
[https://coronadashboard.rijksoverheid.nl/contact](https://coronadashboard.rijksoverheid.nl/contact)
