### ISSUE TITLE
Update Coronadashboard and data.rivm.nl daily 

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#4443]
[Positive tests](https://coronadashboard.government.nl/landelijk/positief-geteste-mensen), [Wastewater](https://coronadashboard.government.nl/landelijk/rioolwater) and [Hospital admissions](https://coronadashboard.government.nl/landelijk/ziekenhuis-opnames) are all rising sharply. The RIVM states that the [upward trend in SARS-CoV-2 infections continues](https://www.rivm.nl/en/news/upward-trend-in-SARS-CoV-2-infections-continues).

Considering this, it would be nice if the data on the Coronadashboard and https://data.rivm.nl/covid-19/ could be updated daily again, including weekends. This will allow the general public, scientists, journalist and policy makers to have access to complete and up to day data.

(I know this isn't strictly an issue of the dashboard, but I would kindly request to pass this on)

**Comment by VWSCoronaDashboard24** [comment]
Hi @EwoutH,

Thank you for your message. We would like to refer you to the attached article. Despite the fact that the autumn wave has started, RIVM sees no reason to increase the frequency of data updates yet. They keep an eye on the virus based on the trends and will only adjust the frequency if the situation requires it.
 
In English:
[Fewer updates, still keeping track of the virus](https://coronadashboard.government.nl/artikelen/minder-vaak-updates-blijvend-oog-op-het-virus)
 
In Dutch:
[Minder vaak updates, blijvend oog op het virus](https://coronadashboard.rijksoverheid.nl/artikelen/minder-vaak-updates-blijvend-oog-op-het-virus)

I hope this helps answering your question. Otherwise let us know!
