### ISSUE TITLE
Reproduction number dashboard has conflicting timestamps

### ISSUE THREAD

**Issue by OnixGH** [minvws/nl-covid19-data-dashboard#462]
1. Currently, the value of the Reproduction number R is 1,33 and is given without a date on the main dashboard:
![image](https://user-images.githubusercontent.com/10709325/94526594-07f63e80-0236-11eb-907e-fe6f5365e5be.png)

2. When clicking through, the top of the page suggests R is: "Value of september 18. Acquired september 22."

![image](https://user-images.githubusercontent.com/10709325/94526364-b64db400-0235-11eb-8b99-2bb7fa77ced4.png)

3. The graph below leaves the date vague again, stating: "Most recent"

![image](https://user-images.githubusercontent.com/10709325/94526777-5572ab80-0236-11eb-8864-5ca7673312c8.png)

4. When hovering over the graph, the most recent plotted R is 1,33 has a timestamp september 4, not september 18.

![image](https://user-images.githubusercontent.com/10709325/94526853-6d4a2f80-0236-11eb-996d-6b691f4130cc.png)

Observations / comments:

- The timestamps in item 2 and 4 conflict with each other. I think perhaps item 2 was meant to say "Voorspelling gemaakt op 18 september".

- Replacing "Most recent" in item 3 with the actual timestamp would be a whole lot more ovbious and clear.

- I would even consider timestamping item 1 in the main dashboard, since the prediction for R always lags a number of weeks behind today, which is very counterintuitive for viewers, since it really doesn't say much about the current situation. It could be a lot higher or lower right now.

**Comment by VWSCoronaDashboard7** [comment]
Hi @OnixGH, thanks for spotting this. What happened was that we were referring to the last value of the entire time series (so a point in the grey area) instead of the last point in the time series where the R value was known. It's correct that there are three dates to consider here:

- 4 september (last known R value)
- 18 september (last date for the predictive part of the time series)
- 22 september (when we last got a data file refresh, containing the time series between 25 aug and 18 sep)

The number on the bar scale in the page refers to 4 sep so this is what most people will likely expect as meta for value from and received as. This is as we had it set prior to the redesign, it must have changed during a refactor. In https://github.com/minvws/nl-covid19-data-dashboard/releases/tag/2.2.0 we've corrected this to match the prior behaviour.

This does mean that currently we omit the 18th as a datapoint in the meta, which might be confusing when looking at the timescales. However we think this is something a user can quickly figure out whilst adding three dates as explained above would only further increase confusion. 

It's a tricky concept and one we're still looking into on how and if we want to resolve it. Whilst splitting it between the tiles or adding a date to the title might help, it will also make the page more text-heavy. Something we try to strike a balance in as to not overwhelm a user with data. Will revisit this issue once we give the design some more thought.

**Comment by OnixGH** [comment]
@VWSCoronaDashboard thanks for the fix, which I think resolves the technical issue, so I'll close this one.

The other points are more design / UX questions; my 2 cents are that it's currently very easy to mistakenly think the displayed R (main dashboard) is "for today" (since all other data pretty much is), whereas it's actually for 2-3 weeks ago. Another confusing thing is that all the other drill down graphs end with "today" on the right side, whereas this one ends at some point in the past where the data happened to have been fetched / updated.
