### ISSUE TITLE
Infection counts don't add up

### ISSUE THREAD

**Issue by kingfisher63** [minvws/nl-covid19-data-dashboard#63]
The new infections counts per veiligheidsregio do not add up to the national count on virtually every single day. Today (2020/07/14) the discrepancy is especially large (93 versus 53). How can we effectively fight this virus if we cannot even get simple numbers right??

**Comment by VWSCoronaDashboard** [comment]
Thanks for reaching out. We’re using RIVM data and a calculation method they’ve provided (and checked) to derive these numbers. This discrepancy is due to the handling of corrections over older data (such as double counts) which differs slightly between the national view and the by safety region view. We’re working on an FAQ or extension of “Cijferverantwoording” in which we will further clarify the calculations taking place.
