### ISSUE TITLE
Prettier config and precommit linter

### ISSUE THREAD

**Issue by JeroenReumkens** [minvws/nl-covid19-data-dashboard#7]
Based on this comment: https://github.com/minvws/nl-covid19-data-dashboard/pull/4#discussion_r437536442

* We should find our where the current Prettier config lives, and added it if necessary. 
* Once it has been added we also would like to add the [Prettier pre-commit hook](https://prettier.io/docs/en/precommit.html) to make enforce the right code style.

**Comment by VWSCoronaDashboard** [comment]
Seems like you're right Jeroen. Something went wrong when copying files from the original repo to the open-source repository. I've got a suspicion that all of our hidden files (such as prettierrc) are missing because we copied files manually through the Finder which hides these files by default.

We'll resolve this as soon as we fully migrate to working from this repository!

**Comment by VWSCoronaDashboard** [comment]
@JeroenReumkens We're not done yet, but this PR should solve this issue in a couple of days! https://github.com/minvws/nl-covid19-data-dashboard/pull/10

**Comment by JeroenReumkens** [comment]
Awesome! And a rewrite to typescript is coming up I see 😍 Love it! 👏 Great work! 
Let me know if there is anything you can use some help with.

**Comment by VWSCoronaDashboard** [comment]
> And a rewrite to typescript is coming up I see 😍

Slowly working towards it, yeah. We'll keep strict flags off and migrate on a file-by-file basis. 👍🏻

**Comment by VWSCoronaDashboard** [comment]
Let's keep the conversation in #10 from now on.
